name: Download new assets

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/10 * * * *'

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install arkprts
        run: python -m pip install arkprts[all]
      - name: install flatbuffers
        run: |
          wget -O flatc.zip https://github.com/google/flatbuffers/releases/download/v24.3.25/Linux.flatc.binary.clang++-15.zip 
          unzip flatc.zip && chmod +x flatc && sudo mv flatc /usr/bin/flatc && rm flatc.zip
      - name: Set flags
        run: |
            CN_VER=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/MooncellWiki/OpenArknightsFBS/commits?sha=main | jq -j '.[0].sha')
            YS_VER=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/MooncellWiki/OpenArknightsFBS/commits?sha=YoStar | jq -j '.[0].sha')
            if [[ $GITHUB_EVENT_NAME == 'workflow_dispatch' || $(cat "fbs_version.txt") == "$CN_VER,$YS_VER" ]]; then
                echo "FLAGS=--force" >> $GITHUB_ENV
            fi
      - name: Update files
        run: python -m arkprts.assets . --server all --log-level DEBUG ${{ env.FLAGS }}
      - name: Save FBS version
        run: echo $(git -C "/tmp/ArknightsFBS/cn/OpenArknightsFBS" rev-parse HEAD),$(git -C "/tmp/ArknightsFBS/yostar/OpenArknightsFBS" rev-parse HEAD) > fbs_version.txt

      - name: Format files
        run: find -name *.json -exec python -m json.tool {} {} --no-ensure-ascii \;
      - name: Check changed directories
        run: git add . && echo "CHANGED_SERVERS=$(git status --porcelain | grep -o -E 'en/|jp/|kr/|cn/|tw/' | sed 's/\/$//' | sort -u | tr '\n' ',' | sed 's/,$//')" >> $GITHUB_ENV

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Arknights update ${{ env.CHANGED_SERVERS }}
