name: Download new assets

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/10 * * * *'

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install arkprts
        run: python -m pip install arkprts[all]
      - name: install flatbuffers
        run: sudo apt-get install -y flatbuffers-compiler
      - name: Update files
        run: python -m arkprts.assets . --server all --log-level DEBUG

      - name: Format files
        run: find -name *.json -exec python -m json.tool {} {} --no-ensure-ascii \;

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Arknights update
          commit_user_name: Silence
